language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: false
after_failure:
  - ls -R
script:
  - sed '/^rustwlc = .*/rustwlc = { git = "https://github.com/SnirkImmington/dummy-rustwlc"/g' Cargo.toml
  - cargo build --verbose
  - cargo test --verbose
